"""empty message

Revision ID: 212a0e8dcf67
Revises: 35e07749aa75
Create Date: 2024-04-30 10:49:36.595841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '212a0e8dcf67'
down_revision = '35e07749aa75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('image_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('captured_user', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
