"""empty message

Revision ID: 22152cec6bc1
Revises: 
Create Date: 2024-04-29 13:09:56.439090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22152cec6bc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
